"""Fordítási táblázat: kulcs -> (magyar, angol)."""

# fmt: off
STRINGS: dict[str, tuple[str, str]] = {
    "decimal_sep": (",", "."),

    # ---- Állapotok -------------------------------------------------------
    "status.pending": ("Várakozik", "Pending"),
    "status.running": ("Folyamatban", "Processing"),
    "status.done": ("Kész", "Done"),
    "status.skipped": ("Kihagyva", "Skipped"),
    "status.failed": ("Hiba", "Failed"),
    "status.cancelled": ("Megszakítva", "Cancelled"),

    "skip.exists": ("a kimeneti fájl már létezik", "output file already exists"),
    "skip.up_to_date": ("a kimeneti fájl naprakész", "output file is up to date"),
    "skip.larger": ("nagyobb lenne, mint az eredeti", "would be larger than the original"),

    "note.renamed": ("átnevezve: {name}", "renamed to {name}"),
    "note.target_quality": ("célméret: minőség {q}%", "target size: quality {q}%"),
    "note.target_not_reached": (
        "a {kb} KB célméret a minimális minőséggel sem érhető el",
        "the {kb} KB target could not be reached even at minimum quality",
    ),
    "note.lossless_no_target": (
        "veszteségmentes módban a célméret nem érvényes",
        "target size is ignored in lossless mode",
    ),

    "warn.icc_failed": (
        "a színprofil átalakítása nem sikerült, az eredeti profil megmarad",
        "colour profile conversion failed, original profile kept",
    ),
    "err.unidentified": ("nem felismerhető vagy sérült képfájl", "unrecognised or corrupt image file"),
    "err.webp_too_large": (
        "a WebP legfeljebb {max}×{max} pixeles lehet (a kép {w}×{h}) – használj átméretezést vagy AVIF-ot",
        "WebP is limited to {max}×{max} pixels (image is {w}×{h}) – resize it or use AVIF",
    ),
    "err.too_many_pixels": ("a kép túl nagy (túl sok pixel)", "image is too large (too many pixels)"),
    "err.memory": ("nincs elég memória a kép feldolgozásához", "not enough memory to process the image"),
    "err.permission": ("hozzáférés megtagadva: {path}", "permission denied: {path}"),
    "err.not_found": ("a fájl nem található: {path}", "file not found: {path}"),
    "err.format_unavailable": (
        "A(z) {fmt} kódoló nem érhető el ebben a telepítésben.",
        "The {fmt} encoder is not available in this installation.",
    ),

    # ---- Presetek ----------------------------------------------------------
    "preset.balanced": ("Kiegyensúlyozott (ajánlott)", "Balanced (recommended)"),
    "preset.balanced.desc": (
        "WebP 80% – jó minőség, jelentős méretcsökkenés",
        "WebP 80% – good quality, significant size reduction",
    ),
    "preset.high_quality": ("Magas minőség", "High quality"),
    "preset.high_quality.desc": (
        "WebP 92%, lassabb, alaposabb tömörítés, EXIF megtartva",
        "WebP 92%, slower thorough compression, EXIF kept",
    ),
    "preset.max_compression": ("Maximális tömörítés", "Maximum compression"),
    "preset.max_compression.desc": (
        "AVIF 45% – a legkisebb fájlméret",
        "AVIF 45% – smallest file size",
    ),
    "preset.web_fullhd": ("Web – Full HD (1920 px)", "Web – Full HD (1920 px)"),
    "preset.web_fullhd.desc": (
        "WebP + AVIF, hosszabbik oldal max. 1920 px, webbarát nevek",
        "WebP + AVIF, long edge max 1920 px, web-safe names",
    ),
    "preset.web_blog": ("Web – blogkép (1200 px széles)", "Web – blog image (1200 px wide)"),
    "preset.web_blog.desc": (
        "WebP + AVIF, 1200 px szélesség, webbarát nevek",
        "WebP + AVIF, 1200 px width, web-safe names",
    ),
    "preset.webshop": ("Webshop termékfotó (1000×1000)", "Web shop product photo (1000×1000)"),
    "preset.webshop.desc": (
        "Beillesztés 1000×1000 px-be, enyhe élesítés",
        "Fit into 1000×1000 px, light sharpening",
    ),
    "preset.thumbnail": ("Bélyegkép (400×400, vágott)", "Thumbnail (400×400, cropped)"),
    "preset.thumbnail.desc": (
        "Középre vágott négyzet, élesítés, „-thumb” utótag",
        "Centre-cropped square, sharpened, “-thumb” suffix",
    ),
    "preset.max_100kb": ("Max. 100 KB / kép", "Max 100 KB per image"),
    "preset.max_100kb.desc": (
        "Automatikus minőségkeresés, hogy minden kép ≤ 100 KB legyen",
        "Automatic quality search so every image is ≤ 100 KB",
    ),
    "preset.lossless": ("Veszteségmentes archiválás", "Lossless archive"),
    "preset.lossless.desc": (
        "WebP veszteségmentes, minden metaadat és színprofil megtartva",
        "Lossless WebP, all metadata and colour profiles kept",
    ),

    # ---- Riport ------------------------------------------------------------
    "report.source": ("Forrás", "Source"),
    "report.format": ("Formátum", "Format"),
    "report.output": ("Kimenet", "Output"),
    "report.status": ("Állapot", "Status"),
    "report.source_bytes": ("Eredeti méret (bájt)", "Original size (bytes)"),
    "report.output_bytes": ("Új méret (bájt)", "New size (bytes)"),
    "report.saving": ("Megtakarítás (%)", "Saving (%)"),
    "report.source_dims": ("Eredeti felbontás", "Original dimensions"),
    "report.output_dims": ("Új felbontás", "New dimensions"),
    "report.quality": ("Minőség", "Quality"),
    "report.seconds": ("Idő (mp)", "Time (s)"),
    "report.message": ("Megjegyzés", "Message"),

    # ---- Parancssor ------------------------------------------------------
    "cli.description": (
        "Képek kötegelt konvertálása WebP és AVIF formátumba.",
        "Batch convert images to WebP and AVIF.",
    ),
    "cli.epilog": (
        "Példák:\n"
        "  webkep-cli kepek -o web\n"
        "  webkep-cli kepek -o web -f webp avif -q 80 --long-edge 1920 --web-safe\n"
        "  webkep-cli kepek -o thumbs --preset thumbnail\n"
        "  webkep-cli kepek -o web --target-kb 150 --report riport.csv",
        "Examples:\n"
        "  webkep-cli photos -o web\n"
        "  webkep-cli photos -o web -f webp avif -q 80 --long-edge 1920 --web-safe\n"
        "  webkep-cli photos -o thumbs --preset thumbnail\n"
        "  webkep-cli photos -o web --target-kb 150 --report report.csv",
    ),
    "cli.inputs": ("bemeneti mappák és/vagy képfájlok", "input folders and/or image files"),
    "cli.output": ("kimeneti mappa", "output folder"),
    "cli.lang": ("a kimenet nyelve", "output language"),
    "cli.list_presets": ("beépített presetek listázása", "list built-in presets"),
    "cli.versions": ("könyvtár- és kodekverziók kiírása", "print library and codec versions"),
    "cli.group.format": ("Formátum és minőség", "Format and quality"),
    "cli.group.resize": ("Átméretezés", "Resizing"),
    "cli.group.meta": ("Metaadatok és szín", "Metadata and colour"),
    "cli.group.naming": ("Fájlnevek és mappák", "File names and folders"),
    "cli.group.run": ("Futtatás", "Execution"),
    "cli.preset": ("kiinduló preset (lásd --list-presets)", "base preset (see --list-presets)"),
    "cli.formats": ("kimeneti formátum(ok), alap: webp", "output format(s), default: webp"),
    "cli.quality": ("minőség 0–100 mindkét formátumra", "quality 0–100 for both formats"),
    "cli.lossless": ("veszteségmentes tömörítés", "lossless compression"),
    "cli.webp_method": ("WebP tömörítési módszer (0 gyors … 6 legjobb)", "WebP method (0 fast … 6 best)"),
    "cli.avif_speed": ("AVIF sebesség (0 lassú/legjobb … 10 leggyorsabb)", "AVIF speed (0 slow/best … 10 fastest)"),
    "cli.no_animation": ("animációk helyett csak az első képkocka", "first frame only instead of animation"),
    "cli.target_kb": ("célméret KB-ban (automatikus minőségkeresés)", "target size in KB (automatic quality search)"),
    "cli.min_quality": ("legkisebb megengedett minőség célméret módban", "lowest allowed quality in target mode"),
    "cli.skip_larger": ("ne mentse, ha nagyobb lenne az eredetinél", "skip if the result is larger than the original"),
    "cli.percent": ("átméretezés százalékosan", "scale by percent"),
    "cli.width": ("szélesség pixelben (arányosan)", "width in pixels (keeps aspect)"),
    "cli.height": ("magasság pixelben (arányosan)", "height in pixels (keeps aspect)"),
    "cli.long_edge": ("hosszabbik oldal max. mérete", "maximum long edge"),
    "cli.fit": ("beillesztés a megadott dobozba, pl. 1920x1080", "fit inside a box, e.g. 1920x1080"),
    "cli.fill": ("pontos méretre vágás középről, pl. 400x400", "centre-crop to exact size, e.g. 400x400"),
    "cli.upscale": ("kisebb képek nagyítása is", "also enlarge smaller images"),
    "cli.sharpen": ("élesítés átméretezés után (alap: 60)", "sharpen after resizing (default: 60)"),
    "cli.keep_exif": ("EXIF metaadatok megtartása", "keep EXIF metadata"),
    "cli.keep_gps": ("GPS helyadatok megtartása (EXIF-fel)", "keep GPS location (with EXIF)"),
    "cli.color": ("színprofil kezelése", "colour profile handling"),
    "cli.no_timestamps": ("ne másolja az eredeti fájldátumot", "do not copy the original file date"),
    "cli.web_safe": ("webbarát fájlnevek (ékezet és szóköz nélkül)", "web-safe file names (no accents/spaces)"),
    "cli.on_conflict": ("teendő, ha a kimeneti fájl létezik", "what to do if the output exists"),
    "cli.no_recursive": ("almappák kihagyása", "do not scan subfolders"),
    "cli.flat": ("minden kimenet egy mappába (szerkezet nélkül)", "all outputs into one folder"),
    "cli.beside_source": ("kimenet a forrásfájlok mellé", "write outputs next to the sources"),
    "cli.types": ("feldolgozandó bemeneti típusok", "input types to process"),
    "cli.workers": ("párhuzamos szálak száma (0 = automatikus)", "parallel workers (0 = auto)"),
    "cli.report": ("CSV riport mentése", "save a CSV report"),
    "cli.dry_run": ("csak kiírja, mi történne", "only show what would happen"),
    "cli.quiet": ("csak a hibák és az összegzés", "only errors and the summary"),
    "cli.err.box": ("Hibás méret: {value} (várt formátum: 800x600)", "Invalid size: {value} (expected e.g. 800x600)"),
    "cli.err.preset": ("Ismeretlen preset: {name}", "Unknown preset: {name}"),
    "cli.err.no_input": ("Adj meg legalább egy bemeneti mappát vagy fájlt.", "Give at least one input folder or file."),
    "cli.err.no_output": (
        "Adj meg kimeneti mappát (-o) vagy használd a --beside-source kapcsolót.",
        "Specify an output folder (-o) or use --beside-source.",
    ),
    "cli.err.missing": ("Nem található: {path}", "Not found: {path}"),
    "cli.no_files": ("Nincs feldolgozható kép.", "No images to process."),
    "cli.start": (
        "{n} kép ({size}) → {fmts}, {workers} szálon",
        "{n} images ({size}) → {fmts}, {workers} workers",
    ),
    "cli.cancelling": ("Leállítás… (újabb Ctrl+C: azonnali kilépés)", "Stopping… (press Ctrl+C again to abort)"),
    "cli.summary": (
        "Kész: {done}, kihagyva: {skipped}, hiba: {failed} – idő: {time}",
        "Done: {done}, skipped: {skipped}, failed: {failed} – time: {time}",
    ),
    "cli.report_written": ("Riport mentve: {path}", "Report saved: {path}"),
    # ---- Általános / fejléc -----------------------------------------------
    "common.close": ("Bezárás", "Close"),
    "preset.label": ("Sablon:", "Preset:"),
    "preset.save": ("Beállítások mentése saját sablonként", "Save settings as a custom preset"),
    "preset.delete": ("Saját sablon törlése", "Delete custom preset"),
    "preset.modified": ("(módosítva)", "(modified)"),
    "preset.name_prompt": ("A sablon neve:", "Preset name:"),
    "preset.overwrite": ("Már létezik „{name}” nevű sablon. Felülírod?", "A preset named “{name}” already exists. Overwrite it?"),
    "preset.delete_confirm": ("Biztosan törlöd a(z) „{name}” sablont?", "Delete the preset “{name}”?"),
    "lang.tooltip": ("Nyelv", "Language"),
    "lang.restart": (
        "A nyelv módosítása az alkalmazás újraindítása után lép érvénybe.",
        "The language change takes effect after restarting the application.",
    ),
    "lang.restart_now": ("Újraindítás most", "Restart now"),
    "lang.later": ("Később", "Later"),
    "theme.toggle": ("Világos / sötét téma", "Light / dark theme"),

    # ---- Mappák -----------------------------------------------------------
    "folders.title": ("Mappák", "Folders"),
    "folders.input": ("Bemeneti mappa (innen olvassa a képeket)", "Input folder (images are read from here)"),
    "folders.output": ("Kimeneti mappa (ide kerülnek a konvertált képek)", "Output folder (converted images go here)"),
    "folders.input_ph": ("Válassz mappát, vagy húzd ide…", "Choose a folder or drop it here…"),
    "folders.output_ph": ("Válassz kimeneti mappát…", "Choose an output folder…"),
    "folders.choose_input": ("Bemeneti mappa kiválasztása", "Choose input folder"),
    "folders.choose_output": ("Kimeneti mappa kiválasztása", "Choose output folder"),
    "folders.recursive": ("Almappák feldolgozása is", "Include subfolders"),
    "folders.recursive_tip": (
        "A bemeneti mappa összes almappájában lévő képet is beolvassa.",
        "Also reads images from every subfolder of the input folder.",
    ),
    "folders.keep_structure": ("Mappaszerkezet megtartása", "Keep folder structure"),
    "folders.keep_structure_tip": (
        "A kimeneti mappában ugyanazok az almappák jönnek létre, mint a forrásban.\n"
        "Kikapcsolva minden kép közvetlenül a kimeneti mappába kerül.",
        "Recreates the source subfolders inside the output folder.\n"
        "When off, every image goes directly into the output folder.",
    ),
    "folders.beside": ("Mentés a forrásfájlok mellé", "Save next to the source files"),
    "folders.beside_tip": (
        "A konvertált kép ugyanabba a mappába kerül, ahol az eredeti van\n"
        "(pl. kep.jpg mellé kep.webp) – hasznos <picture> elemes weboldalakhoz.",
        "The converted image is written next to the original\n"
        "(e.g. photo.webp beside photo.jpg) – handy for <picture> markup.",
    ),
    "picker.browse": ("Tallózás…", "Browse…"),
    "picker.recent": ("Legutóbbi mappák", "Recent folders"),
    "picker.no_recent": ("(nincs korábbi mappa)", "(no recent folders)"),

    # ---- Fájllista ----------------------------------------------------------
    "files.title": ("Fájlok", "Files"),
    "files.none": ("nincs fájl", "no files"),
    "files.count": ("{n} kép · {size}", "{n} images · {size}"),
    "files.count_checked": ("{c} / {n} kijelölve · {size}", "{c} / {n} selected · {size}"),
    "files.filter_ph": ("Szűrés névre…", "Filter by name…"),
    "files.all_status": ("Minden állapot", "All statuses"),
    "files.add": ("Fájlok hozzáadása", "Add files"),
    "files.rescan": ("Mappa újraolvasása", "Rescan folder"),
    "files.preview": ("Előnézet és összehasonlítás", "Preview and compare"),
    "files.clear": ("Lista ürítése", "Clear list"),
    "files.images": ("Képek", "Images"),
    "files.drop_hint": ("Húzz ide egy mappát vagy képeket", "Drop a folder or images here"),
    "files.drop_sub": (
        "…vagy válassz bemeneti mappát fent. Támogatott: JPG, PNG, BMP, GIF, TIFF, HEIC, WebP, AVIF és továbbiak.",
        "…or choose an input folder above. Supported: JPG, PNG, BMP, GIF, TIFF, HEIC, WebP, AVIF and more.",
    ),
    "col.name": ("Fájl", "File"),
    "col.type": ("Típus", "Type"),
    "col.dims": ("Felbontás", "Dimensions"),
    "col.size": ("Méret", "Size"),
    "col.status": ("Állapot", "Status"),
    "col.webp": ("WebP", "WebP"),
    "col.avif": ("AVIF", "AVIF"),
    "col.saving": ("Változás", "Change"),
    "tip.quality": ("minőség {q}%", "quality {q}%"),
    "tip.resized": ("átméretezve: {a} → {b}", "resized: {a} → {b}"),
    "menu.preview": ("Előnézet", "Preview"),
    "menu.open_file": ("Megnyitás", "Open"),
    "menu.open_folder": ("Tartalmazó mappa megnyitása", "Open containing folder"),
    "menu.open_result": ("Konvertált kép megnyitása", "Open converted image"),
    "menu.check_selected": ("Kijelöltek bejelölése", "Check selected"),
    "menu.uncheck_selected": ("Kijelöltek kivétele", "Uncheck selected"),
    "menu.check_all": ("Mind bejelöl", "Check all"),
    "menu.check_none": ("Egyiket sem", "Check none"),
    "menu.check_failed": ("Csak a hibásak bejelölése (újrapróbáláshoz)", "Check only failed (to retry)"),
    "menu.remove": ("Eltávolítás a listából", "Remove from list"),

    # ---- Napló / állapotsor ------------------------------------------------
    "log.title": ("Napló", "Log"),
    "log.clear": ("Napló törlése", "Clear log"),
    "log.scanned": ("{n} kép ({size}) beolvasva: {path}", "{n} images ({size}) found in {path}"),
    "log.files_added": ("{n} fájl hozzáadva a listához", "{n} files added to the list"),
    "log.output_suggested": ("Javasolt kimeneti mappa: {path}", "Suggested output folder: {path}"),
    "log.preset_applied": ("Sablon betöltve: {name}", "Preset applied: {name}"),
    "log.preset_saved": ("Saját sablon mentve: {name}", "Custom preset saved: {name}"),
    "log.quality_applied": ("{fmt} minőség beállítva: {q}%", "{fmt} quality set to {q}%"),
    "log.start": ("Konvertálás indul: {n} kép → {fmts}, {workers} szálon", "Starting: {n} images → {fmts}, {workers} workers"),
    "log.target_mode": ("Célméret mód: legfeljebb {kb} KB / kép", "Target size mode: at most {kb} KB per image"),
    "log.paused": ("Szüneteltetve – a folyamatban lévő képek még befejeződnek.", "Paused – images in progress will still finish."),
    "log.resumed": ("Folytatás.", "Resumed."),
    "log.stopping": ("Leállítás… a folyamatban lévő képek befejeződnek.", "Stopping… images in progress will finish."),
    "log.finished": (
        "Kész! Sikeres: {done}, kihagyva: {skipped}, hiba: {failed} – idő: {time}",
        "Finished! Converted: {done}, skipped: {skipped}, failed: {failed} – time: {time}",
    ),
    "log.finished_cancelled": (
        "Leállítva. Sikeres: {done}, kihagyva: {skipped}, hiba: {failed} – idő: {time}",
        "Stopped. Converted: {done}, skipped: {skipped}, failed: {failed} – time: {time}",
    ),
    "log.report_saved": ("Riport mentve ({n} sor): {path}", "Report saved ({n} rows): {path}"),
    "status.ready": ("Kész a munkára. Válassz bemeneti mappát!", "Ready. Choose an input folder!"),
    "status.scanning": ("Mappa beolvasása…", "Scanning folder…"),
    "status.reading": ("Képadatok olvasása: {done} / {total}", "Reading image info: {done} / {total}"),
    "status.found": ("{n} kép található ({size})", "{n} images found ({size})"),
    "status.input_missing": ("A bemeneti mappa nem létezik: {path}", "Input folder does not exist: {path}"),

    # ---- Futtatás ----------------------------------------------------------
    "btn.start": ("Konvertálás indítása", "Start conversion"),
    "btn.running": ("Folyamatban…", "Running…"),
    "btn.pause": ("Szünet", "Pause"),
    "btn.resume": ("Folytatás", "Resume"),
    "btn.stop": ("Leállítás", "Stop"),
    "btn.open_output": ("Kimeneti mappa", "Output folder"),
    "btn.export": ("Riport (CSV)", "Report (CSV)"),
    "btn.estimate": ("Méretbecslés", "Estimate size"),
    "btn.estimating": ("Becslés…", "Estimating…"),
    "btn.estimate_tip": (
        "Néhány mintaképet a memóriában konvertál, és megbecsüli a várható teljes kimeneti méretet.",
        "Converts a few sample images in memory and estimates the total output size.",
    ),
    "run.ready": ("{n} kép vár konvertálásra", "{n} images ready to convert"),
    "run.progress": ("{done} / {total} kép", "{done} / {total} images"),
    "run.eta": ("Eltelt: {elapsed} · Hátralévő: ~{eta} · {rate} kép/mp", "Elapsed: {elapsed} · Remaining: ~{eta} · {rate} img/s"),
    "run.elapsed": ("Eltelt: {elapsed}", "Elapsed: {elapsed}"),
    "run.paused": ("Szüneteltetve", "Paused"),
    "run.summary": ("Sikeres: {done} · kihagyva: {skipped} · hiba: {failed}", "Converted: {done} · skipped: {skipped} · failed: {failed}"),
    "run.total_time": ("Teljes idő: {time}", "Total time: {time}"),
    "err.no_format": ("Válassz legalább egy kimeneti formátumot (WebP vagy AVIF)!", "Select at least one output format (WebP or AVIF)!"),
    "err.no_files": ("Nincs kijelölt, feldolgozható kép a listában.", "There are no checked images to process."),
    "err.no_output": ("Adj meg egy kimeneti mappát!", "Please choose an output folder!"),
    "err.output_not_writable": ("A kimeneti mappa nem írható:\n{path}\n\n{err}", "The output folder is not writable:\n{path}\n\n{err}"),
    "close.running": (
        "A konvertálás még folyamatban van. Leállítod és kilépsz?",
        "A conversion is still running. Stop it and quit?",
    ),

    # ---- Beállítások: fülek -------------------------------------------------
    "tab.format": ("Formátum", "Format"),
    "tab.resize": ("Méret", "Size"),
    "tab.meta": ("Metaadat", "Metadata"),
    "tab.output": ("Kimenet", "Output"),
    "tab.advanced": ("Haladó", "Advanced"),

    "fmt.output_formats": ("Kimeneti formátum", "Output format"),
    "fmt.webp_tip": (
        "WebP: minden modern böngésző támogatja, gyors kódolás, kb. 25–35%-kal kisebb a JPEG-nél.",
        "WebP: supported by every modern browser, fast to encode, ~25–35% smaller than JPEG.",
    ),
    "fmt.avif_tip": (
        "AVIF: még kisebb fájlok (akár 50% a JPEG-hez képest), de lassabb kódolás.",
        "AVIF: even smaller files (up to 50% vs JPEG), but slower to encode.",
    ),
    "fmt.both_hint": (
        "Mindkettő bejelölésével minden képből WebP és AVIF változat is készül (pl. <picture> elemhez).",
        "Check both to create a WebP and an AVIF version of every image (e.g. for <picture>).",
    ),
    "fmt.keep_animation": ("Animációk megtartása (GIF → animált kép)", "Keep animations (GIF → animated image)"),
    "fmt.keep_animation_tip": (
        "Kikapcsolva az animált képekből csak az első képkocka készül el.",
        "When off, only the first frame of animated images is converted.",
    ),
    "q.quality": ("Minőség", "Quality"),
    "q.quality_tip": (
        "Minél kisebb a minőség, annál kisebb a fájl, de annál jobban „butul” a kép.\n"
        "A 100% − minőség adja a tömörítés (butítás) mértékét.",
        "Lower quality means smaller files but more visible degradation.\n"
        "100% − quality is the amount of compression loss.",
    ),
    "q.smaller": ("kisebb fájl", "smaller file"),
    "q.better": ("jobb minőség", "better quality"),
    "q.caption": ("{label} · butítás: {loss}%", "{label} · loss: {loss}%"),
    "q.lossless_caption": ("Veszteségmentes – a kép pixelre pontosan megmarad", "Lossless – pixel-perfect result"),
    "q.excellent": ("Kiváló minőség, szemmel alig látható eltérés", "Excellent, virtually indistinguishable"),
    "q.very_good": ("Nagyon jó – ajánlott webre", "Very good – recommended for the web"),
    "q.good": ("Jó, erősebb tömörítés", "Good, stronger compression"),
    "q.medium": ("Közepes, látható minőségromlás", "Medium, visible degradation"),
    "q.low": ("Alacsony, erős butítás", "Low, heavy degradation"),
    "webp.lossless": ("Veszteségmentes tömörítés", "Lossless compression"),
    "webp.lossless_tip": (
        "Pixelre pontos eredmény – logókhoz, grafikákhoz, képernyőképekhez ideális.\n"
        "Ilyenkor a minőség csúszka a tömörítés alaposságát szabályozza.",
        "Pixel-perfect result – ideal for logos, graphics and screenshots.\n"
        "In this mode the quality slider controls compression effort.",
    ),
    "webp.method": ("Tömörítési módszer", "Compression method"),
    "webp.method_tip": (
        "0 = leggyorsabb, 6 = leglassabb, de a legkisebb fájl azonos minőség mellett.",
        "0 = fastest, 6 = slowest but smallest file at the same quality.",
    ),
    "webp.faster": ("gyorsabb", "faster"),
    "webp.smaller": ("kisebb fájl", "smaller file"),
    "webp.alpha_quality": ("Átlátszóság minősége", "Alpha quality"),
    "webp.alpha_quality_tip": (
        "Az átlátszósági (alfa) csatorna tömörítésének minősége. 100% = veszteségmentes.",
        "Compression quality of the transparency (alpha) channel. 100% = lossless.",
    ),
    "webp.exact": ("Színek megőrzése átlátszó részeken", "Keep colours in transparent areas"),
    "webp.exact_tip": (
        "Az teljesen átlátszó pixelek színét is megőrzi (nagyobb fájl). Csak speciális esetben kell.",
        "Keeps the RGB values of fully transparent pixels (larger file). Rarely needed.",
    ),
    "avif.lossless": ("Közel veszteségmentes (100%, 4:4:4)", "Near-lossless (100%, 4:4:4)"),
    "avif.lossless_tip": (
        "Maximális minőség teljes színfelbontással. A fájl jóval nagyobb lesz.",
        "Maximum quality with full chroma resolution. Files will be much larger.",
    ),
    "avif.speed": ("Kódolási sebesség", "Encoding speed"),
    "avif.speed_tip": (
        "0 = nagyon lassú, de a legkisebb fájl · 10 = leggyorsabb. 4–6 jó kompromisszum.",
        "0 = very slow but smallest file · 10 = fastest. 4–6 is a good balance.",
    ),
    "avif.slower": ("lassabb, kisebb fájl", "slower, smaller"),
    "avif.faster": ("gyorsabb", "faster"),
    "avif.subsampling": ("Színmintavételezés", "Chroma subsampling"),
    "avif.subsampling_tip": (
        "4:2:0: legkisebb fájl, fotókhoz tökéletes · 4:4:4: éles színhatárok (grafikák, szöveg).",
        "4:2:0: smallest files, perfect for photos · 4:4:4: crisp colour edges (graphics, text).",
    ),
    "avif.sub.420": ("4:2:0 – legkisebb fájl (ajánlott)", "4:2:0 – smallest file (recommended)"),
    "avif.sub.422": ("4:2:2 – kiegyensúlyozott", "4:2:2 – balanced"),
    "avif.sub.444": ("4:4:4 – legjobb színhűség", "4:4:4 – best colour fidelity"),
    "avif.scale_hint": (
        "Tipp: az AVIF minőségskálája eltér a WebP-étől – az AVIF 60% nagyjából a WebP 80%-ának felel meg.",
        "Tip: AVIF quality is on a different scale – AVIF 60% is roughly WebP 80%.",
    ),

    "rs.title": ("Átméretezés", "Resize"),
    "rs.mode": ("Mód", "Mode"),
    "rs.mode.none": ("Nincs átméretezés", "No resizing"),
    "rs.mode.percent": ("Százalékos méretezés", "Scale by percent"),
    "rs.mode.width": ("Megadott szélesség", "Fixed width"),
    "rs.mode.height": ("Megadott magasság", "Fixed height"),
    "rs.mode.long_edge": ("Hosszabbik oldal max. mérete", "Maximum long edge"),
    "rs.mode.fit": ("Beillesztés dobozba (max. szél. × mag.)", "Fit inside box (max W × H)"),
    "rs.mode.fill": ("Kitöltés és vágás pontos méretre", "Fill and crop to exact size"),
    "rs.percent": ("Méret", "Scale"),
    "rs.width": ("Szélesség", "Width"),
    "rs.height": ("Magasság", "Height"),
    "rs.long_edge": ("Hosszabbik oldal", "Long edge"),
    "rs.box_width": ("Szélesség", "Width"),
    "rs.box_height": ("Magasság", "Height"),
    "rs.upscale": ("Kisebb képek nagyítása is", "Also enlarge smaller images"),
    "rs.upscale_tip": (
        "Alapesetben a célméretnél kisebb képek érintetlenek maradnak (nagyítás rontja a minőséget).",
        "By default images smaller than the target are left untouched (upscaling reduces quality).",
    ),
    "rs.example": ("Példa:", "Example:"),
    "rs.unchanged": ("nem változik", "unchanged"),
    "rs.quality_title": ("Méretezés minősége", "Resampling quality"),
    "rs.filter": ("Szűrő", "Filter"),
    "rs.filter_tip": (
        "A Lanczos a legélesebb, fotókhoz ajánlott. A „legközelebbi” pixel-arthoz való.",
        "Lanczos is the sharpest and recommended for photos. Nearest is for pixel art.",
    ),
    "rs.filter.lanczos": ("Lanczos – legjobb minőség", "Lanczos – best quality"),
    "rs.filter.bicubic": ("Bikubikus", "Bicubic"),
    "rs.filter.bilinear": ("Bilineáris – gyors", "Bilinear – fast"),
    "rs.filter.nearest": ("Legközelebbi szomszéd – pixel art", "Nearest neighbour – pixel art"),
    "rs.sharpen": ("Élesítés átméretezés után", "Sharpen after resizing"),
    "rs.sharpen_tip": (
        "Kicsinyítés után a kép kissé lágyabb lehet – az enyhe élesítés ezt ellensúlyozza.",
        "Downscaled images can look slightly soft – light sharpening compensates.",
    ),
    "rs.sharpen_amount": ("Erősség", "Amount"),
    "rs.subtle": ("finom", "subtle"),
    "rs.strong": ("erős", "strong"),

    "md.title": ("Metaadatok", "Metadata"),
    "md.auto_orient": ("Automatikus elforgatás (EXIF alapján)", "Auto-rotate (from EXIF)"),
    "md.auto_orient_tip": (
        "A telefonnal készült, „oldalra dőlt” fotókat a helyes állásba forgatja.",
        "Rotates phone photos that would otherwise appear sideways.",
    ),
    "md.keep_exif": ("EXIF megtartása (gép, dátum, expozíció)", "Keep EXIF (camera, date, exposure)"),
    "md.keep_exif_tip": (
        "Webre általában felesleges – eltávolítva kisebb a fájl és nem kerül ki személyes adat.",
        "Usually unnecessary on the web – removing it saves bytes and protects privacy.",
    ),
    "md.strip_gps": ("GPS helyadatok eltávolítása", "Remove GPS location"),
    "md.strip_gps_tip": (
        "Adatvédelem: a fotó készítésének helye nem kerül bele a kimeneti fájlba.",
        "Privacy: the location where the photo was taken is not included in the output.",
    ),
    "md.keep_xmp": ("XMP megtartása (címkék, szerzői jog)", "Keep XMP (keywords, copyright)"),
    "md.keep_xmp_tip": (
        "Az Adobe/Lightroom által írt kiegészítő metaadatok (pl. szerző, kulcsszavak).",
        "Additional metadata written by Adobe/Lightroom (e.g. author, keywords).",
    ),
    "md.timestamps": ("Eredeti fájldátum megtartása", "Keep original file date"),
    "md.timestamps_tip": (
        "A konvertált fájl módosítási dátuma megegyezik az eredetiével (fotóalbumokhoz hasznos).",
        "The converted file gets the same modification date as the original (useful for photo albums).",
    ),
    "md.privacy_hint": (
        "Alapértelmezésben minden metaadat törlődik: kisebb fájl, és nem szivárog ki személyes adat.",
        "By default all metadata is removed: smaller files and no leaked personal data.",
    ),
    "md.color_title": ("Színkezelés", "Colour management"),
    "md.color": ("Színprofil", "Colour profile"),
    "md.color.srgb": ("Átalakítás sRGB-re (ajánlott webre)", "Convert to sRGB (best for web)"),
    "md.color.keep": ("Eredeti profil beágyazása", "Embed original profile"),
    "md.color.strip": ("Profil eltávolítása átalakítás nélkül", "Remove profile without conversion"),
    "md.color_hint": (
        "Az Adobe RGB / Display P3 képeket az sRGB-átalakítás teszi helyes színűvé minden böngészőben.",
        "Converting Adobe RGB / Display P3 images to sRGB keeps colours correct in every browser.",
    ),

    "nm.title": ("Fájlnevek", "File names"),
    "nm.prefix": ("Előtag", "Prefix"),
    "nm.suffix": ("Utótag", "Suffix"),
    "nm.prefix_ph": ("pl. web-", "e.g. web-"),
    "nm.suffix_ph": ("pl. -min", "e.g. -min"),
    "nm.web_safe": ("Webbarát nevek (ékezet és szóköz nélkül)", "Web-safe names (no accents or spaces)"),
    "nm.web_safe_tip": ("„Nyári Fotó 01.JPG” → „nyari-foto-01.webp”", "“Summer Photo 01.JPG” → “summer-photo-01.webp”"),
    "nm.lowercase": ("Kisbetűs fájlnevek", "Lowercase file names"),
    "nm.conflict": ("Ha a fájl már létezik", "If the file exists"),
    "nm.conflict_tip": (
        "Mi történjen, ha a kimeneti mappában már van ilyen nevű fájl.\n"
        "A „csak ha a forrás újabb” opcióval gyorsan frissíthető egy korábbi konvertálás.",
        "What to do when a file with the same name already exists in the output folder.\n"
        "“Only if source is newer” makes re-running a previous job quick.",
    ),
    "nm.conflict.overwrite": ("Felülírás", "Overwrite"),
    "nm.conflict.skip": ("Kihagyás", "Skip"),
    "nm.conflict.rename": ("Átnevezés (kep_1, kep_2…)", "Rename (image_1, image_2…)"),
    "nm.conflict.update": ("Csak ha a forrás újabb", "Only if source is newer"),
    "nm.example": ("Példa:", "Example:"),
    "nm.sample_name": ("Nyári Fotó 01.JPG", "Summer Photo 01.JPG"),

    "sz.title": ("Fájlméret", "File size"),
    "sz.target": ("Maximális fájlméret (célméret mód)", "Maximum file size (target mode)"),
    "sz.target_tip": (
        "Képenként automatikusan megkeresi a legjobb minőséget, amivel a fájl még belefér a megadott méretbe.",
        "Automatically finds the best quality per image that still fits the given size.",
    ),
    "sz.max_size": ("Legfeljebb", "At most"),
    "sz.min_quality": ("Legkisebb minőség", "Minimum quality"),
    "sz.min_quality_tip": (
        "Ennél rosszabb minőségre nem megy le a keresés; ha így sem fér bele, a legkisebb változat készül el.",
        "The search never goes below this; if the size still can't be met, the smallest version is kept.",
    ),
    "sz.skip_larger": ("Ne mentse, ha nagyobb, mint az eredeti", "Skip if larger than the original"),
    "sz.skip_larger_tip": (
        "Ritkán, de előfordul (pl. már erősen tömörített képeknél), hogy a konvertált fájl nagyobb.",
        "Occasionally (e.g. already heavily compressed images) the converted file is larger.",
    ),
    "sz.hint": (
        "Célméret módban képenként több próbakódolás fut, így a konvertálás lassabb (főleg AVIF-nál).",
        "Target mode runs several trial encodes per image, so conversion is slower (especially AVIF).",
    ),

    "adv.types": ("Feldolgozandó fájltípusok", "File types to process"),
    "adv.types_hint": (
        "A WebP és AVIF bemenet alapból ki van kapcsolva, hogy a korábban konvertált képek ne kerüljenek újra feldolgozásra.",
        "WebP and AVIF inputs are off by default so previously converted images are not processed again.",
    ),
    "type.jpeg": ("JPEG", "JPEG"),
    "type.jpeg.tip": (".jpg .jpeg .jpe .jfif", ".jpg .jpeg .jpe .jfif"),
    "type.png": ("PNG", "PNG"),
    "type.png.tip": (".png (APNG animációval is)", ".png (including APNG animation)"),
    "type.bmp": ("BMP", "BMP"),
    "type.bmp.tip": (".bmp .dib", ".bmp .dib"),
    "type.gif": ("GIF", "GIF"),
    "type.gif.tip": (".gif (animációval is)", ".gif (including animation)"),
    "type.tiff": ("TIFF", "TIFF"),
    "type.tiff.tip": (".tif .tiff", ".tif .tiff"),
    "type.webp": ("WebP", "WebP"),
    "type.webp.tip": (".webp – újratömörítéshez", ".webp – for recompression"),
    "type.avif": ("AVIF", "AVIF"),
    "type.avif.tip": (".avif – újratömörítéshez", ".avif – for recompression"),
    "type.heic": ("HEIC / HEIF", "HEIC / HEIF"),
    "type.heic.tip": (".heic .heif – iPhone fotók", ".heic .heif – iPhone photos"),
    "type.heic.unavailable": ("A HEIC támogatás nem érhető el (pi-heif hiányzik).", "HEIC support is unavailable (pi-heif missing)."),
    "type.other": ("Egyéb", "Other"),
    "type.other.tip": (".ico .tga .ppm .pgm .pbm .pnm .jp2 .j2k .psd", ".ico .tga .ppm .pgm .pbm .pnm .jp2 .j2k .psd"),
    "adv.performance": ("Teljesítmény", "Performance"),
    "adv.workers": ("Párhuzamos szálak", "Parallel workers"),
    "adv.workers_auto": ("Automatikus ({n} mag)", "Automatic ({n} cores)"),
    "adv.workers_tip": (
        "Hány képet dolgozzon fel egyszerre. Az automatikus a processzormagok száma.\n"
        "Kevés memória esetén (nagyon nagy képeknél) érdemes csökkenteni.",
        "How many images are processed at once. Automatic uses the number of CPU cores.\n"
        "Lower it on low-memory machines with very large images.",
    ),
    "adv.after": ("Befejezéskor", "When finished"),
    "adv.open_output": ("Kimeneti mappa megnyitása", "Open the output folder"),
    "adv.notify": ("Összegzés megjelenítése", "Show summary"),
    "adv.reset": ("Konverziós beállítások visszaállítása", "Reset conversion settings"),

    # ---- Előnézet ----------------------------------------------------------
    "pv.title": ("Előnézet és összehasonlítás", "Preview and compare"),
    "pv.prev": ("Előző kép (←)", "Previous image (←)"),
    "pv.next": ("Következő kép (→)", "Next image (→)"),
    "pv.format": ("Formátum:", "Format:"),
    "pv.fit": ("Illesztés az ablakhoz (F)", "Fit to window (F)"),
    "pv.actual": ("Eredeti méret, 100% (1)", "Actual size, 100% (1)"),
    "pv.zoom_in": ("Nagyítás", "Zoom in"),
    "pv.zoom_out": ("Kicsinyítés", "Zoom out"),
    "pv.original": ("Eredeti", "Original"),
    "pv.original_resized": ("Eredeti (átméretezve, tömörítés nélkül)", "Original (resized, uncompressed)"),
    "pv.working": ("Számítás…", "Working…"),
    "pv.loading": ("Betöltés…", "Loading…"),
    "pv.lossless": ("veszteségmentes", "lossless"),
    "pv.encode_time": ("kódolás: {t} mp", "encoding: {t} s"),
    "pv.hint": (
        "Görgess a nagyításhoz, húzd a képet a mozgatáshoz – a két nézet együtt mozog.",
        "Scroll to zoom, drag to pan – both views move together.",
    ),
    "pv.apply": ("Minőség alkalmazása a beállításokra", "Apply quality to settings"),

    # ---- Összegzés / becslés / névjegy ----------------------------------------
    "sum.title": ("Összegzés", "Summary"),
    "sum.success": ("Kész! Minden kép elkészült.", "Done! All images converted."),
    "sum.with_errors": ("Kész, de néhány képnél hiba történt.", "Done, but some images failed."),
    "sum.cancelled": ("A konvertálás leállítva.", "Conversion stopped."),
    "sum.subtitle": ("{n} kép feldolgozva, teljes idő: {time}", "{n} images processed, total time: {time}"),
    "sum.done": ("sikeres", "converted"),
    "sum.skipped": ("kihagyva", "skipped"),
    "sum.failed": ("hiba", "failed"),
    "sum.files": ("új fájl", "files written"),
    "sum.sizes": ("Méretek", "Sizes"),
    "sum.format_line": ("{n} kép: {src} → {out}", "{n} images: {src} → {out}"),
    "sum.errors": ("Hibák:", "Errors:"),
    "sum.more": ("…és még {n} további", "…and {n} more"),
    "est.title": ("Méretbecslés", "Size estimate"),
    "est.intro": (
        "{sampled} mintakép alapján a kijelölt {n} kép ({size}) várható kimeneti mérete:",
        "Based on {sampled} sample images, the expected output size of the {n} selected images ({size}):",
    ),
    "est.line": ("≈ {out}", "≈ {out}"),
    "est.none": ("A mintaképek nem voltak konvertálhatók.", "The sample images could not be converted."),
    "est.note": (
        "A becslés tájékoztató jellegű; a tényleges eredmény a képek tartalmától függ.",
        "This is an estimate; the actual result depends on image content.",
    ),
    "about.title": ("Névjegy", "About"),
    "about.version": ("Verzió {v}", "Version {v}"),
    "about.description": (
        "Kötegelt képkonvertáló webre: JPG, PNG, BMP, GIF, TIFF, HEIC és más formátumok gyors, párhuzamos "
        "átalakítása WebP és AVIF formátumba, átméretezéssel, metaadat- és színkezeléssel.",
        "Batch image converter for the web: fast, parallel conversion of JPG, PNG, BMP, GIF, TIFF, HEIC and more "
        "to WebP and AVIF, with resizing, metadata and colour management.",
    ),
    "about.libraries": ("Könyvtárak és kodekek", "Libraries and codecs"),
    "about.shortcuts": ("Billentyűparancsok", "Keyboard shortcuts"),
    "about.shortcuts_text": (
        "<b>Ctrl+Enter</b> konvertálás indítása · <b>Esc</b> leállítás · <b>F5</b> újraolvasás<br>"
        "<b>Ctrl+O</b> bemeneti mappa · <b>Ctrl+Shift+O</b> kimeneti mappa · <b>Ctrl+P</b> előnézet<br>"
        "<b>Ctrl+F</b> szűrés · <b>F1</b> névjegy",
        "<b>Ctrl+Enter</b> start · <b>Esc</b> stop · <b>F5</b> rescan<br>"
        "<b>Ctrl+O</b> input folder · <b>Ctrl+Shift+O</b> output folder · <b>Ctrl+P</b> preview<br>"
        "<b>Ctrl+F</b> filter · <b>F1</b> about",
    ),
}
# fmt: on
